# Generated by Django 5.2 on 2025-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_demandeprojet_alter_realisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeprojet',
            name='indicatif',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demandeprojet',
            name='numero_sans_indicatif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
