# Generated by Django 5.2 on 2025-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_demandeprojet_indicatif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FilePathField(blank=True, match='.*\\.(jpg|jpeg|png|gif|svg)$', null=True, path='static/image/realisations/', recursive=True)),
                ('alt_field', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
