# Generated by Django 5.2 on 2025-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.FilePathField(blank=True, match='.*\\.(jpg|jpeg|png|gif|svg)$', null=True, path='/image/services/', recursive=True),
        ),
    ]
