# Generated by Django 5.2 on 2025-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/services/'),
        ),
    ]
