# Generated by Django 5.2 on 2025-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_realisation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/realisations/'),
        ),
    ]
